name: chatzy
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <4.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_app_check: ^0.2.2+7
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: 6.0.0
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
  dotted_line: ^3.2.2
  country_list_pick: ^1.0.1+6
  pinput: ^3.0.1
  dotted_border: ^2.1.0
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  firebase_storage: ^11.5.6
  cloud_firestore: ^4.13.6
  device_info_plus: ^9.1.1
  fluttertoast: ^8.2.4
  image_picker: ^1.0.5
  launch_review: ^3.0.1
  permission_handler:
  url_launcher: ^6.2.2
  figma_squircle: ^0.5.3
  encrypt: ^5.0.3
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  flutter_image_compress: ^2.1.0
  flutter_sound: ^9.2.13
  video_player: ^2.8.1
  open_filex: ^4.3.4
  dio: ^5.4.0
  dartx: ^1.2.0
  geolocator: ^10.1.0
  audioplayers: ^5.2.1
  path_provider: ^2.1.1
  flutter_native_image: ^0.0.6+1
  image_cropper:
  light_compressor: ^2.2.0
  audio_video_progress_bar: ^2.0.1
  connectivity_plus: ^5.0.2
  emoji_picker_flutter: ^1.6.3
  advance_pdf_viewer_fork:
  giphy_get:
  audio_waveforms: ^1.0.4
  video_compress: ^3.1.2
  image_gallery_saver: ^2.0.3
  photo_view: ^0.14.0
  any_link_preview: any
  flutter_switch: ^0.3.2
  local_auth: ^2.1.7
  share_plus: ^7.2.1
  story_view: ^0.16.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  localstorage: ^4.0.1+4
  scoped_model: ^2.0.0
  flutter_local_notifications: ^16.2.0
  camera: ^0.10.5+7
  async: ^2.11.0
  agora_rtc_engine: ^6.2.6
  cloud_functions: ^4.6.5
  wakelock_plus: ^1.1.4
  fast_contacts: ^3.1.3
  country_codes: ^2.2.0
  timezone: ^0.9.2
  simple_app_cache_manager: ^0.0.4
  contacts_service: ^0.6.3
  zego_uikit_prebuilt_live_audio_room: ^3.7.5
  zego_uikit_prebuilt_live_streaming: 2.23.0

dependency_overrides:
  country_state_city_picker: 1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - assets/gif/